# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - group: app-one
  - name: region
    value: 'us-east-2'
  - name: erc-repo-name
    value: 'app-one'
  - name: profile
    value: 'AppOneProfile'
trigger:
  - scafolding
  
pool:
    vmImage: ubuntu-latest
  
steps:
  - task: PowerShell@2
    displayName: 'Check and install AWS.Tools.Installer and AWS.Tools.Common modules'
    inputs:
      filePath: 'InstallAWSTools.ps1'

  # - task: PowerShell@2
  #   displayName: 'Verify docker version'
  #   inputs:
  #       targetType: 'inline'
  #       script: 'docker --version'

  - task: PowerShell@2
    displayName: 'Set AWS Credentail'
    inputs:
      targetType: 'inline'
      script: 'Set-AWSCredential -AccessKey $(App-One.AccessKey) `
                -SecretKey $(App-One.SecretKey) `
                -StoreAs $(profile)'

  - task: PowerShell@2
    displayName: 'Check if Amazon ECR repository exists'
    inputs:
      targetType: 'inline'
      script: |
        if ($RepositoryName -ne ((Get-ECRRepository -ProfileName $(profile) -Region $(region)) | where-object {$_.RepositoryName -eq $(erc-repo-name)}).RepositoryName)
        {
          New-ECRRepository -ImageScanningConfiguration_ScanOnPush true -ImageTagMutability true -ProfileName $(profile) -Region $(region) -RepositoryName $(erc-repo-name)
        } else {
          Write-Host "Repository $(erc-repo-name) already exists."
        }
  # - task: PowerShell@2
  #   displayName: 'Docker login'
  #   inputs:
  #     targetType: 'inline'
  #     script: '(Get-ECRLoginCommand -ProfileName $(profile) -Region $(region)).Password | docker login --username AWS --password-stdin 635656952828.dkr.ecr.$(region).amazonaws.com'
  
  # - task: PowerShell@2
  #   displayName: 'Build docker image'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'docker build -t $(erc-repo-name) .'

  # - task: PowerShell@2
  #   displayName: 'Tag docker image'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'docker tag $(erc-repo-name):latest 635656952828.dkr.ecr.$(region).amazonaws.com/$(erc-repo-name):latest'

  # - task: PowerShell@2
  #   displayName: 'Push docker image to ECR'
  #   inputs:
  #     targetType: 'inline'
  #     script: 'docker push 635656952828.dkr.ecr.$(region).amazonaws.com/$(erc-repo-name):latest'

  - task: PowerShell@2
    displayName: 'Remove AWS Credentail'
    inputs:
      targetType: 'inline'
      script: 'Remove-AWSCredentialProfile -ProfileName $(profile) -Force'
    condition: always()